In [371]:
X=[[1.,0.],[0.,0.],[1.,1.],[0.,1.]]
y=[1,0,0,1]

In [377]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(3,2),activation='logistic',solver='lbfgs',alpha=1e-6)

In [378]:
mlp.fit(X,y)

MLPClassifier(activation='logistic', alpha=1e-06, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(3, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [379]:
mlp.loss_

0.00023429449717907272

In [380]:
mlp.coefs_

[array([[-10.06925317,  -3.27454771,  -1.48086906],
        [-15.2460576 ,  -2.26591233,  -2.07083604]]),
 array([[ -9.43036472,  14.53560919],
        [  1.14762739, -15.33131541],
        [ -0.11037107,  -1.00823802]]),
 array([[ -2.0868292 ],
        [-26.19425212]])]

In [381]:
mlp.intercepts_

[array([ 3.50007092,  2.95012454, -3.81005295]),
 array([ 2.2893021 ,  2.38754685]),
 array([ 12.44206412])]

In [382]:
print(mlp.predict([[0.,0.]]))

[0]


In [516]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [517]:
names=['Sex','Length','Diameter','Height','Whole weight','Shucked weight','Viscera weight','Shell weight','Rings']
df=pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data",names=names)

In [518]:
encoder = preprocessing.LabelEncoder()
df["Sex"]=encoder.fit_transform(df["Sex"])

In [665]:
from sklearn.preprocessing import StandardScaler
columns=[i for i in names if i != 'Rings']
dfcopy=df.copy()
features=dfcopy[columns]
scaler = StandardScaler().fit(features.values)
features = scaler.transform(features.values)
dfcopy[columns]=features
dfcopy

Sex    Length  Diameter    Height  Whole weight  Shucked weight  \
0     1.151980 -0.574558 -0.432149 -1.064424     -0.641898       -0.607685   
1     1.151980 -1.448986 -1.439929 -1.183978     -1.230277       -1.170910   
2    -1.280690  0.050033  0.122130 -0.107991     -0.309469       -0.463500   
3     1.151980 -0.699476 -0.432149 -0.347099     -0.637819       -0.648238   
4    -0.064355 -1.615544 -1.540707 -1.423087     -1.272086       -1.215968   
5    -0.064355 -0.824395 -1.087206 -1.064424     -0.973307       -0.983919   
6    -1.280690  0.050033  0.071741  0.250672     -0.104505       -0.551363   
7    -1.280690  0.174951  0.172519 -0.347099     -0.123880       -0.294533   
8     1.151980 -0.408000 -0.381760 -0.347099     -0.651076       -0.643732   
9    -1.280690  0.216591  0.323686  0.250672      0.134109       -0.202164   
10   -1.280690  0.008394 -0.280982  0.011563     -0.453250       -0.745112   
11    1.151980 -0.782755 -0.583316 -0.705762     -0.862158       -0.864516   
12    1.151980 -0.283082 -0.280982 -0.107991     -0.585814       -0.639226   
13   -1.280690  0.091673 -0.029037  0.131117     -0.294173       -0.391407   
14   -1.280690 -0.449640 -0.532927 -0.944870     -0.720417       -0.864516   
15    1.151980 -0.199803 -0.079426 -0.227545     -0.334962       -0.456741   
16   -0.064355 -1.407346 -1.288762 -1.303532     -1.097713       -1.191186   
17   -1.280690 -0.699476 -0.684094 -0.944870     -0.770383       -0.772147   
18    1.151980 -1.324068 -1.137595 -1.423087     -1.169094       -1.182174   
19    1.151980 -0.616198 -0.885650 -0.944870     -0.913144       -0.850998   
20    1.151980 -1.407346 -1.288762 -1.064424     -1.189488       -1.188933   
21   -0.064355 -1.199149 -1.339151 -0.944870     -1.230277       -1.258773   
22   -1.280690  0.341509  0.323686  0.370226      0.225884        0.306991   
23   -1.280690  0.216591  0.071741 -0.107991     -0.133058       -0.186393   
24   -1.280690  0.757903  0.726798  0.609334      0.678640        0.692237   
25   -1.280690  0.299870  0.323686  0.011563      0.203450        0.104230   
26   -1.280690  0.466427  0.424464  1.087551      0.340093        0.158300   
27    1.151980  0.549706  0.374075  0.011563      0.208549       -0.015173   
28    1.151980  0.674624  0.676409  0.967997      0.219766        0.156047   
29    1.151980  0.424788  0.172519  0.011563      0.070887        0.151541   
...        ...       ...       ...       ...           ...             ...   
4147  1.151980  1.424134  1.432245  1.326659      1.704479        1.656477   
4148  1.151980  2.048725  1.986524  0.848442      2.491704        1.987653   
4149 -0.064355 -2.031938 -1.943819 -1.662195     -1.437280       -1.335371   
4150 -0.064355 -1.615544 -1.792652 -1.423087     -1.404649       -1.364659   
4151 -0.064355 -1.448986 -1.591096 -1.542641     -1.344486       -1.243003   
4152 -0.064355 -1.282428 -1.288762 -1.183978     -1.245573       -1.170910   
4153 -0.064355 -0.782755 -0.936039 -0.586208     -0.907026       -0.769894   
4154 -0.064355 -0.741116 -0.784872 -1.064424     -0.888671       -0.632467   
4155 -0.064355 -0.699476 -0.583316 -0.705762     -0.914164       -0.909574   
4156  1.151980 -0.408000 -0.381760 -0.705762     -0.691865       -0.634720   
4157  1.151980 -0.408000 -0.482538  0.011563     -0.642918       -0.533340   
4158 -0.064355 -0.366361 -0.532927 -0.705762     -0.773442       -0.713572   
4159 -1.280690  0.299870  0.323686 -0.107991     -0.053519       -0.042208   
4160 -1.280690  0.508067  0.676409  0.609334      0.457361        0.444418   
4161 -1.280690  0.508067  0.474853  0.728888      0.338053        0.297980   
4162  1.151980 -1.157510 -1.540707 -0.944870     -1.042648       -1.001942   
4163 -0.064355 -1.115871 -0.986428 -1.303532     -0.988603       -0.803687   
4164 -0.064355 -1.115871 -1.187984 -0.944870     -1.109950       -1.053759   
4165 -0.064355 -0.990952 -1.087206 -1.303532     -1.071201       -0.943367   
4166 -0.064355 -0.408000 -0.43214

In [666]:
X=dfcopy[columns]
y=dfcopy['Rings']

In [671]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print(X_train)

           Sex    Length  Diameter    Height  Whole weight  Shucked weight  \
2830 -1.280690  0.008394  0.222908 -0.107991      0.030098        0.329520   
925  -0.064355 -0.782755 -0.835261 -0.944870     -0.946795       -0.909574   
3845  1.151980 -0.574558 -0.583316 -0.825316     -0.841763       -0.887045   
547   1.151980 -2.656529 -2.548487 -2.259966     -1.603495       -1.542638   
2259 -1.280690  0.549706  0.575631  0.489780      0.554234        0.660696   
3588  1.151980  1.049379  1.079522  1.087551      1.113041        1.760110   
1450 -0.064355 -0.574558 -0.734483 -0.107991     -0.668411       -0.384648   
2827 -0.064355 -0.199803 -0.331371 -0.466653     -0.611307       -0.612191   
2233  1.151980  0.591345  0.676409  0.728888      0.546076        0.268692   
611   1.151980 -2.739808 -2.649265 -2.140412     -1.624909       -1.574179   
2337  1.151980  0.299870  0.474853  0.609334      0.063749        0.189840   
3896  1.151980  1.965446  1.684190  1.207105      2.039967      

In [753]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(200,100,100), random_state=1,max_iter=5000,activation='logistic',solver='lbfgs',alpha=0.4)
print(clf)
clf.fit(X_train, y_train)
print(clf.loss_)
print(clf.n_iter_)

MLPClassifier(activation='logistic', alpha=0.4, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(200, 100, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=5000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
1.13201352938
5001


In [754]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score
train_pred=clf.predict(X_train)
print(accuracy_score(y_train,train_pred))
test_predictions = clf.predict(X_test)
print(accuracy_score(y_test,test_predictions))
#print(classification_report(y_test,predictions))

0.959630516593
0.232854864434
